### ISSUE TITLE
Installation link is broken

### ISSUE THREAD

**Issue by jscott0** [juga0/opgpcard#1]
README.rst links to [here](https://github.com/juga0/opgpcard/blob/master/install.html) which doesn't exist, and so I'm having trouble finding installation directions.

**Comment by juga0** [comment]
Thanks for reporting this bug.
The bug is due a relative link that in Github points to an inexistent page but it works when the documentation is built locally.
The solution is include relative links for several sources.
While i fix this bug, you can see the install page at https://github.com/juga0/opgpcard/blob/master/docs/source/install.rst.
If you use Debian, it's recommended that you install it from the Debian package. Note that there're other known bugs that affect to the Debian package and will be fixed soon, as https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=926108.
